const GitHubModelsClient = require('./githubModelsClient');
const db = require('../../../../database/models/db');

/**
 * LLM-First SQL Generator
 * Converts natural language to SQL using complete schema awareness
 */
class SQLGenerator {
  constructor(mandt) {
    this.mandt = mandt;
    this.aiClient = new GitHubModelsClient();
  }

  /**
   * Generate SQL query from natural language using LLM
   */
  async generateSQL(question) {
    try {
      const systemPrompt = this.getSchemaAwarePrompt();
      
      const messages = [
        { role: 'system', content: systemPrompt },
        { 
          role: 'user', 
          content: `Convert this question to a PostgreSQL query for mandt='${this.mandt}': ${question}

IMPORTANT: 
- Always include mandt='${this.mandt}' in WHERE clause
- Return ONLY the SQL query, no explanations
- Use proper JOINs for related data
- Limit results to 50 rows for safety
- Use exact table and column names from the schema` 
        }
      ];

      console.log('[SQLGenerator] Generating SQL for:', question);
      
      const response = await this.aiClient.chat(messages, {
        temperature: 0.1, // Low temperature for precise SQL generation
        max_tokens: 500
      });

      let sql = response.choices[0]?.message?.content?.trim();
      
      if (!sql) {
        throw new Error('No SQL generated by LLM');
      }

      // Clean up the SQL - remove markdown code blocks if present
      sql = sql.replace(/```sql\n?/gi, '').replace(/```\n?/g, '').trim();
      
      // Basic security validation
      if (this.isSafeSQL(sql)) {
        console.log('[SQLGenerator] Generated SQL:', sql);
        return sql;
      } else {
        throw new Error('Generated SQL failed security validation');
      }

    } catch (error) {
      console.error('[SQLGenerator] LLM SQL generation failed:', error.message);
      throw error;
    }
  }

  /**
   * Execute SQL query and return formatted results
   */
  async executeQuery(sql) {
    try {
      console.log('[SQLGenerator] Executing SQL:', sql);
      const result = await db.query(sql);
      
      return {
        success: true,
        data: result.rows,
        count: result.rows.length,
        sql: sql
      };
    } catch (error) {
      console.error('[SQLGenerator] SQL execution failed:', error.message);
      return {
        success: false,
        error: error.message,
        sql: sql
      };
    }
  }

  /**
   * Fallback queries for when LLM fails
   */
  getFallbackQuery(question) {
    const q = question.toLowerCase();
    
    // Common fallback patterns
    if (q.includes('sold') && (q.includes('state') || q.includes('status'))) {
      return `
        SELECT mandt, sgtin, gtin, product_name, brand, category, status, location, batch, manufacture_date, created_at
        FROM v_inventory 
        WHERE mandt = '${this.mandt}' AND status = 'SOLD'
        ORDER BY created_at DESC 
        LIMIT 50
      `;
    }
    
    if (q.includes('in stock') || q.includes('inventory')) {
      return `
        SELECT mandt, sgtin, gtin, product_name, brand, category, status, location, batch, manufacture_date, created_at
        FROM v_inventory 
        WHERE mandt = '${this.mandt}' AND status = 'IN_STOCK'
        ORDER BY created_at DESC 
        LIMIT 50
      `;
    }
    
    // Enhanced purchase order handling with time-based filtering
    if (q.includes('purchase order') || q.includes('po')) {
      // Check for time-based queries
      if (q.includes('hour') || q.includes('today') || q.includes('recent')) {
        // Use PostgreSQL's proper interval syntax for accurate time filtering
        let timeFilter = '';
        if (q.includes('1 hour') || q.includes('last hour')) {
          timeFilter = "AND created_at >= NOW() - INTERVAL '1 hour'";
        } else if (q.includes('today')) {
          timeFilter = "AND DATE(created_at) = CURRENT_DATE";
        } else {
          timeFilter = "AND created_at >= NOW() - INTERVAL '24 hours'"; // Default to last 24 hours for "recent"
        }
        
        return `
          SELECT mandt, po_id, gtin, product_name, brand, quantity, received_quantity, status, supplier, warehouse, expected_delivery_date, created_at
          FROM v_purchase_orders 
          WHERE mandt = '${this.mandt}' ${timeFilter}
          ORDER BY created_at DESC 
          LIMIT 50
        `;
      }
      
      // Default PO query without time filter
      return `
        SELECT mandt, po_id, gtin, product_name, brand, quantity, received_quantity, status, supplier, warehouse, expected_delivery_date, created_at
        FROM v_purchase_orders 
        WHERE mandt = '${this.mandt}'
        ORDER BY created_at DESC 
        LIMIT 50
      `;
    }
    
    if (q.includes('counterfeit') || q.includes('fraud')) {
      return `
        SELECT mandt, log_id, sgtin, reason, store_id, detected_at, details
        FROM counterfeit_logs 
        WHERE mandt = '${this.mandt}'
        ORDER BY detected_at DESC 
        LIMIT 50
      `;
    }
    
    // Default fallback - show recent inventory
    return `
      SELECT mandt, sgtin, gtin, product_name, brand, category, status, location, created_at
      FROM v_inventory 
      WHERE mandt = '${this.mandt}'
      ORDER BY created_at DESC 
      LIMIT 20
    `;
  }

  /**
   * Main method: Generate and execute SQL
   */
  async processQuestion(question) {
    try {
      // Try LLM first
      const sql = await this.generateSQL(question);
      const result = await this.executeQuery(sql);
      
      if (result.success) {
        return {
          method: 'llm_generated',
          ...result
        };
      } else {
        console.log('[SQLGenerator] LLM query failed, trying fallback...');
        // If LLM query fails, try fallback
        const fallbackSQL = this.getFallbackQuery(question);
        const fallbackResult = await this.executeQuery(fallbackSQL);
        
        return {
          method: 'fallback_query',
          ...fallbackResult
        };
      }
    } catch (error) {
      console.log('[SQLGenerator] LLM generation failed, using fallback...');
      // If LLM generation fails completely, use fallback
      const fallbackSQL = this.getFallbackQuery(question);
      const fallbackResult = await this.executeQuery(fallbackSQL);
      
      return {
        method: 'fallback_query',
        ...fallbackResult
      };
    }
  }

  /**
   * Security validation for generated SQL
   */
  isSafeSQL(sql) {
    const sqlLower = sql.toLowerCase();
    
    // Block dangerous operations
    const dangerousKeywords = [
      'drop', 'delete', 'update', 'insert', 'alter', 'create', 'truncate',
      'grant', 'revoke', 'exec', 'execute', 'sp_', 'xp_', '--', '/*', '*/',
      'union', 'into outfile', 'load_file', 'system', 'shell'
    ];
    
    for (const keyword of dangerousKeywords) {
      if (sqlLower.includes(keyword)) {
        console.warn('[SQLGenerator] Blocked dangerous SQL keyword:', keyword);
        return false;
      }
    }
    
    // Must be a SELECT statement
    if (!sqlLower.trim().startsWith('select')) {
      console.warn('[SQLGenerator] SQL must start with SELECT');
      return false;
    }
    
    // Must include mandt filter
    if (!sqlLower.includes(`mandt = '${this.mandt}'`) && !sqlLower.includes(`mandt='${this.mandt}'`)) {
      console.warn('[SQLGenerator] SQL must include mandt filter');
      return false;
    }
    
    return true;
  }

  /**
   * Complete database schema prompt for LLM
   */
  getSchemaAwarePrompt() {
    return `You are a PostgreSQL query generator for an SGTIN (Serial Global Trade Item Number) Lifecycle Management System.

# DATABASE SCHEMA

## Core Tables:

### products (Master product data)
- mandt VARCHAR(3) - tenant ID  
- gtin VARCHAR(14) - Global Trade Item Number
- name VARCHAR(255) - product name
- brand VARCHAR(100)
- category VARCHAR(100) 
- subcategory VARCHAR(100)
- price DECIMAL(10,2)
- description TEXT
- created_at TIMESTAMP
- updated_at TIMESTAMP
PRIMARY KEY: (mandt, gtin)

### serialized_items (Individual serialized items)
- mandt VARCHAR(3) - tenant ID
- sgtin VARCHAR(50) - Serialized GTIN (unique identifier)
- gtin VARCHAR(14) - links to products table
- status VARCHAR(20) - ENUM: 'CREATED', 'IN_STOCK', 'SOLD', 'RETURNED', 'DAMAGED'
- location VARCHAR(100) - warehouse/store location
- batch VARCHAR(50)
- manufacture_date DATE
- passport JSONB - additional metadata
- barcode TEXT
- qr_code TEXT  
- created_at TIMESTAMP
- updated_at TIMESTAMP
PRIMARY KEY: (mandt, sgtin)

### purchase_orders (Purchase order headers)
- mandt VARCHAR(3) - tenant ID
- po_id VARCHAR(20) - purchase order ID
- gtin VARCHAR(14) - product being ordered
- quantity INTEGER - total quantity ordered
- received_quantity INTEGER - quantity received so far
- status VARCHAR(20) - ENUM: 'OPEN', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CANCELLED'
- supplier VARCHAR(255)
- warehouse VARCHAR(100)
- expected_delivery_date DATE
- created_at TIMESTAMP
- updated_at TIMESTAMP
PRIMARY KEY: (mandt, po_id)

### po_sgtin_mapping (Maps SGTINs to purchase orders)
- mandt VARCHAR(3)
- po_id VARCHAR(20)
- sgtin VARCHAR(50)
- created_at TIMESTAMP
PRIMARY KEY: (mandt, po_id, sgtin)

### sales (Sales transaction headers)
- mandt VARCHAR(3)
- sale_id VARCHAR(20)
- store_id VARCHAR(20)
- cashier_id VARCHAR(20)
- total_amount DECIMAL(10,2)
- sold_at TIMESTAMP
PRIMARY KEY: (mandt, sale_id)

### sale_items (Individual items in sales)
- mandt VARCHAR(3)
- sale_id VARCHAR(20)
- sgtin VARCHAR(50)
- price DECIMAL(10,2)
- created_at TIMESTAMP
PRIMARY KEY: (mandt, sale_id, sgtin)

### lifecycle_events (Audit trail for SGTINs)
- mandt VARCHAR(3)
- event_id UUID
- sgtin VARCHAR(50)
- event_type VARCHAR(20) - ENUM: 'CREATED', 'RECEIVED', 'SOLD', 'RETURNED', 'DAMAGED', 'RECALLED'
- location VARCHAR(100)
- metadata JSONB
- created_at TIMESTAMP
PRIMARY KEY: (mandt, event_id)

### counterfeit_logs (Counterfeit detection logs)
- mandt VARCHAR(3)
- log_id UUID
- sgtin VARCHAR(50)
- reason VARCHAR(50) - ENUM: 'NOT_FOUND', 'ALREADY_SOLD', 'WRONG_STORE', 'INVALID_FORMAT'
- store_id VARCHAR(20)
- detected_at TIMESTAMP
- details JSONB
PRIMARY KEY: (mandt, log_id)

## Useful Views (Pre-joined for convenience):

### v_inventory (Inventory with product details)
- All serialized_items columns + product_name, brand, category from products

### v_purchase_orders (Purchase orders with product details)  
- All purchase_orders columns + product_name, brand from products

### v_sales_details (Sales with product details)
- sale_id, store_id, sgtin, gtin, product_name, brand, price, sold_at

# QUERY GENERATION RULES:

1. ALWAYS include mandt filter in WHERE clause
2. Use proper JOINs when combining tables
3. Prefer views (v_inventory, v_purchase_orders, v_sales_details) for common queries
4. LIMIT results to 50 rows maximum for performance
5. Use exact column names and table names as specified
6. Handle case-insensitive searches with ILIKE for text fields
7. For time-based filters, use PostgreSQL INTERVAL syntax: NOW() - INTERVAL '1 hour'

# COMMON QUERY PATTERNS:

**Inventory queries**: Use v_inventory view, filter by status
**Purchase order queries**: Use v_purchase_orders view, filter by status/supplier
**Sales queries**: Use v_sales_details view with date ranges
**Item tracking**: Join serialized_items with lifecycle_events
**Counterfeit detection**: Query counterfeit_logs table

# TIME-BASED QUERY EXAMPLES:

**Last hour**: WHERE created_at >= NOW() - INTERVAL '1 hour'
**Today**: WHERE DATE(created_at) = CURRENT_DATE
**Last 24 hours**: WHERE created_at >= NOW() - INTERVAL '24 hours'
**Last week**: WHERE created_at >= NOW() - INTERVAL '7 days'

Generate efficient, safe PostgreSQL queries that answer the user's question accurately.`;
  }
}

module.exports = SQLGenerator;